overwrite: false

prefer_grub_d: false

keep_distributor: false

kernel_params: [ "quiet","nowatchdog" ]

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: true
    GRUB_TERMINAL_OUTPUT: "gfxterm"
    GRUB_GFXMODE: "auto"
    GRUB_GFXPAYLOAD_LINUX: "keep"
    GRUB_THEME: "/usr/share/grub/themes/limalinux/theme.txt"
    GRUB_DISTRIBUTOR: "LimaLinux"
    GRUB_DISABLE_RECOVERY: true
