---
groupsUrl:
  - "https://raw.githubusercontent.com/limalinuxos/limalinux_calamares_config/main/etc/calamares/modules/netinstall-desktops.yaml"
  - "file:///etc/calamares/modules/netinstall-desktops-offline.yaml"

showInitial: true
required: false

label:
  sidebar: "Desktops"
  title: "Desktops"
