---
groupsUrl:
  - "https://raw.githubusercontent.com/limalinuxos/limalinux_calamares_config/main/etc/calamares/modules/netinstall-system.yaml"
  - "file:///etc/calamares/modules/netinstall-system-offline.yaml"

showInitial: true
required: false

label:
  sidebar: "System"
  title: "System"
