---
groupsUrl:
  - "https://raw.githubusercontent.com/limalinuxos/limalinux_calamares_config/main/etc/calamares/modules/netinstall-dev.yaml"
  - "file:///etc/calamares/modules/netinstall-dev-offline.yaml"

showInitial: true
required: false

label:
  sidebar: "Dev"
  title: "Dev"
