---

groupsUrl: "https://raw.githubusercontent.com/limalinuxos/limalinux_calamares_config/main/etc/calamares/modules/netinstall.yaml"

showInitial: true
required: false

label:
    sidebar: "Software"
    title: "Apps selection"


id: choice
