#!/bin/bash
set -e

echo "Instalando dependencias reales de Arch para Calamares (Qt6)..."

# Nombres correctos para Arch Linux (KDE Frameworks 6)
sudo pacman -S --noconfirm --needed \
    qt6-base \
    qt6-declarative \
    qt6-tools \
    qt6-svg \
    qt6-translations \
    extra-cmake-modules \
    kconfig \
    kcoreaddons \
    kpackage \
    kparts \
    kwidgetsaddons \
    ki18n \
    kpmcore \
    boost-libs \
    yaml-cpp \
    dmidecode \
    hwinfo \
    icu \
    libpwquality \
    squashfs-tools \
    polkit-qt6

echo "Instalando dependencias adicionales de AUR..."
# Asegúrate de tener ckbcomp y mkinitcpio-openswap
yay -S --noconfirm --needed mkinitcpio-openswap ckbcomp

echo "################################################################"
echo "### Dependencias corregidas instaladas"
echo "################################################################"
