modules-search: [ local ]

instances:
- id: rootfs
  module:   unpackfs
  config:   unpackfs1.conf
  weight:   45
- id: vmlinuz
  module:   unpackfs
  config:   unpackfs2.conf
  weight:   5
- id: choice
  module:   packages
  config:   packages.conf
  weight:   25
- id:       dracut
  module:   shellprocess
  config:   shellprocess_dracut.conf
  weight:   10
- id:       final
  module:   shellprocess
  config:   shellprocess-final.conf
  weight:   25
- id:       net_desktops
  module:   netinstall
  config:   netinstall-desktops.conf
- id:       net_internet
  module:   netinstall
  config:   netinstall-internet.conf
- id:       net_media
  module:   netinstall
  config:   netinstall-media.conf
- id:       net_dev
  module:   netinstall
  config:   netinstall-dev.conf
- id:       net_ai
  module:   netinstall
  config:   netinstall-ai.conf
- id:       net_system
  module:   netinstall
  config:   netinstall-system.conf

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - netinstall@net_desktops
    - netinstall@net_internet
    - netinstall@net_media
    - netinstall@net_dev
    - netinstall@net_ai
    - netinstall@net_system
    - summary
- exec:
    - partition
    - mount
    - unpackfs@rootfs
    - unpackfs@vmlinuz
    - machineid
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - luksopenswaphookcfg
    - fstab
    - networkcfg
    - limalinux_before       
    - limalinux_remove_nvidia
    - shellprocess@dracut 
    # removeuser → users → displaymanager antes de services-systemd (GDM / liveuser)
    - hwclock
    - removeuser
    - users
    - displaymanager
    - services-systemd
    - packages@choice
    - limalinux_ucode
    - grubcfg
    - bootloader
    - shellprocess@final
    - limalinux_final         
    - preservefiles
    - umount
- show:
    - finished
    

branding: limalinux

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
